name: Build and publish the Docker image

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Standard permission for GitHub Actions

on:
  push:
    tags:
      - "[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9].[1-9]"

jobs:
  publish-to-aws-ecr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-manager
    env:
      ENV: prod
      SERVICE_NAME: ${{ vars.PRIVATEECR_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with AWS ECR account for pushing the image
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ECR_PUBLISH_ROLE_ARN }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: Authenticate with AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and publish the Docker image to AWS ECR
        run: make deploy
